### ISSUE TITLE
support for maxDepth

### ISSUE THREAD

**Issue by chantastic** [DSchau/gatsby-remark-toc#1]
👋 hi

curious if you have plans to support `maxDepth`. I'd customarily just fork this type of thing and patch it myself but I am so far out of my depth with how Gatsby and Remark plugins get resolved.

if you don't plan on adding support for `maxDepth` could you point me in a direction for rolling my own wrapper around [mdast-util-toc](https://www.npmjs.com/package/mdast-util-toc)?

thanks!

**Comment by DSchau** [comment]
Hey!! 👋 

This should be a super simple fix, and something I probably should've allowed to begin with.

I'm not sure of the best approach as to supporting it, but I should allow some nested key to be passed to mdast-util-toc directly. Then we can pass [`maxDepth`, `heading` (a search string), and `tight`](https://www.npmjs.com/package/mdast-util-toc#options) as well.

So technically how we'd do it is pretty simple. We need to standardize on what that key should be (e.g. `mdastUtilTocOptions`) and then we simply pass it to the plugin.

1. [These are the options](https://github.com/DSchau/gatsby-remark-toc/blob/master/src/index.js#L6) as passed from `gastby-config.js`
    - We'd need to add a new key here (or object rest/spread, I'm not too opinionated here!)
1. Pass those options to [gatsby-remark-toc](https://github.com/DSchau/gatsby-remark-toc/blob/master/src/index.js#L18) as the second argument

I can take a look at this later today, otherwise hopefully that's helpful? Should be a really easy and worthwhile change, so thanks for making me aware of it!

**Comment by DSchau** [comment]
Hi Michael--great talk at React Rally by the way, wish we had a chance to chat!

Published with 1.1.0, lemme know if it works for you :) Thanks!

**Comment by chantastic** [comment]
Oh thanks! That talk is the reason I fell off the planet for the bit and never got back to you. Sorry about that 😬.

Thanks for publishing the changes and allowing those values to be passed through!

Do you plan (have a ticket) to got to React Conf this year?

**Comment by DSchau** [comment]
Ha, not a problem at all!

I _wish_ but did not get one 😢 Did you?

**Comment by chantastic** [comment]
I was able to get one by pestering people who got them but weren't able to go 😬.

If you end up going, it'd be fun to record something where we talk about css-in-js and your css-in-js-playground

**Comment by DSchau** [comment]
Damn, I need to expand my circle so I can do the same ;)

I will definitely let you know! I would love to chat about that sometime either there or elsewhere!
